FROM node:20-alpine

WORKDIR /usr/src/app

# Only copy package files first to leverage Docker cache
COPY package*.json ./
RUN npm install

# Copy the rest of the code
COPY . .

EXPOSE 3000
CMD ["npm", "run", "dev"]