FROM golang:1.22-alpine

WORKDIR /app

# Install git for dependencies if needed
RUN apk add --no-cache git

COPY go.mod go.sum ./
RUN go mod download

COPY . .

# Build the app
RUN go build -o main .

CMD ["./main"]